unit NCService_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}
{$I LibFun.inc}
interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes,
  {$IFDEF RO_v90}uROProxy,{$ENDIF}uROClientIntf;

const
  { Library ID }
  LibraryUID = '{D8AC5B06-795A-4BE8-A852-D360405ED62D}';
  TargetNamespace = '';

  { Service Interface ID's }
  IItfZxtoNcData_IID : TGUID = '{F4CB678A-846F-4E66-989F-28196624CC96}';
  ItfZxtoNcData_EndPointURI = 'http://10.1.104.231/uapws/service/nc.itf.zx.salepreorder.ItfZxtoNcData';

  { Event ID's }

type
  { Forward declarations }
  IItfZxtoNcData = interface;


  { IItfZxtoNcData }
  IItfZxtoNcData = interface
    ['{F4CB678A-846F-4E66-989F-28196624CC96}']
    function operationSaveorderTime(const string0: WideString; const string1: WideString): WideString;
  end;

  { CoItfZxtoNcData }
  CoItfZxtoNcData = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IItfZxtoNcData;
  end;

  { TItfZxtoNcData_Proxy }
  TItfZxtoNcData_Proxy = class(TROProxy, IItfZxtoNcData)
  protected
    function __GetInterfaceName:string; override;

    function operationSaveorderTime(const string0: WideString; const string1: WideString): WideString;
  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoItfZxtoNcData }

class function CoItfZxtoNcData.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IItfZxtoNcData;
begin
  result := TItfZxtoNcData_Proxy.Create(aMessage, aTransportChannel);
end;

{ TItfZxtoNcData_Proxy }

function TItfZxtoNcData_Proxy.__GetInterfaceName:string;
begin
  result := 'ItfZxtoNcData';
end;

function TItfZxtoNcData_Proxy.operationSaveorderTime(const string0: WideString; const string1: WideString): WideString;
begin
    __Message.SetAttributes(__TransportChannel, ['action', 'inputchildrennamespace', 'location', 'outputchildrennamespace', 'remap_operationsaveordertime', 'soapinputmessagenamespace', 'soapinputnameoverride'
      , 'soapoutputmessagenamespace', 'style', 'type', 'use'], 
      ['urn:operationSaveorderTime', '*', 'http://10.1.104.231/uapws/service/nc.itf.zx.salepreorder.ItfZxtoNcData', '*', 'urn:operationSaveorderTime', 'http://salepreorder.zx.itf.nc/ItfZxtoNcData', 'operationSaveorderTime'
      , 'http://salepreorder.zx.itf.nc/ItfZxtoNcData', 'document', 'SOAP', 'literal']);
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'NCService', __InterfaceName, 'operationSaveorderTime');
    __Message.Write('string', TypeInfo(WideString), string0, []);
    __Message.Write('string1', TypeInfo(WideString), string1, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('return', TypeInfo(WideString), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

initialization
  RegisterProxyClass(IItfZxtoNcData_IID, TItfZxtoNcData_Proxy);


finalization
  UnregisterProxyClass(IItfZxtoNcData_IID);

end.
